# deploy mkdocs site
name: Deploy
description: 'deploys mkdocs site to S3'
inputs:
  version:
    description: 'Build version to deploy.  Used to get archive at unique S3 key.  Ex: sha-####, 3.0.0'
    required: true
    type: string
  env-name:
    description: 'Environment name.  Ex: dev, prod'
    default: 'dev'
    required: true
    type: string
  s3-bucket:
    description: 'S3 Bucket to deploy to.'
    required: true
    type: string
  aws-region:
    description: 'AWS Region.  Ex: us-east-1'
    default: 'us-east-1'
    required: true
    type: string                      
  aws-access-key-id:
    description: 'AWS Access Key ID.'
    required: true
    type: string
  aws-secret-access-key:
    description: 'AWS Secret Access Key.'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }} 
    - name: Get Site Artifact
      shell: bash
      run: |
        make get-mkdocs-archive env=${{ inputs.env-name }} region=${{ inputs.aws-region }} version=${{ inputs.version }} 
    - name: Deploy Site
      shell: bash
      run: |
        make deploy-mkdocs env=${{ inputs.env-name }} region=${{ inputs.aws-region }} bucket-name=${{ inputs.s3-bucket }}
