# deploy mkdocs site
name: Deploy
description: 'deploys mkdocs site to S3'
inputs:
  version:
    description: 'Build version to deploy.  Used to get archive at unique S3 key.  Ex: sha-####, 3.0.0'
    required: true
    type: string
  env-name:
    description: 'Environment name.  Ex: dev, prod'
    default: 'dev'
    required: true
    type: string
  s3-bucket:
    description: 'S3 Bucket to deploy to.'
    required: true
    type: string
  make-vars:
    description: 'Variables to pass to all make commands.  Ex: `--no-print-directory` would result in `make --no-print-directory get-mkdocs-archive...` See README.md for details.'
    default: "--no-print-directory"
    required: false
    type: string
  make-vars-for-deploy-target:
    description: 'Variables to pass to `deploy-mkdocs` make command.  Ex: `QUIET=1` would result in `make QUIET=1 deploy-mkdocs...` See README.md for details.'
    default: ""
    required: false
    type: string
  aws-region:
    description: 'AWS Region.  Ex: us-east-1'
    default: 'us-east-1'
    required: true
    type: string                      
  aws-access-key-id:
    description: 'AWS Access Key ID.'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key.'
    required: false
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: false
  role-duration-seconds:
    description: "Role duration in seconds (default: 6 hours, 1 hour for OIDC/specified aws-session-token)"
    required: false
  role-session-name:
    description: 'Role session name (default: GitHubActions)'
    required: false
  role-external-id:
    description: 'The external ID of the role to assume'
    required: false
  role-skip-session-tagging:
    description: 'Skip session tagging during role assumption'
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}
        role-session-name: ${{ inputs.role-session-name }}
        role-external-id: ${{ inputs.role-external-id }}
        role-skip-session-tagging: ${{ inputs.role-skip-session-tagging }}
    - name: Get Site Artifact
      shell: bash
      run: |
        make ${{ inputs.make-vars }} get-mkdocs-archive env=${{ inputs.env-name }} region=${{ inputs.aws-region }} version=${{ inputs.version }} download-directory="$RUNNER_TEMP/"
    - name: Deploy Site
      shell: bash
      run: |
        make ${{ inputs.make-vars }} ${{ inputs.make-vars-for-deploy-target }} deploy-mkdocs env=${{ inputs.env-name }} region=${{ inputs.aws-region }} bucket-name=${{ inputs.s3-bucket }}
